# Generated by Django 6.0.2 on 2026-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiDjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='Category',
            new_name='category',
        ),
    ]
